"""Run the demonstration scenarios in both governance modes and write a transcript.

    PYTHONPATH=. python scripts/demo.py demo_transcript.md
"""
from __future__ import annotations

import sys
import tempfile

from docdrift.app import build_pipeline
from docdrift.config import Settings
from docdrift.corpus import build_corpus
from docdrift.governance import GovernanceMode

SCENARIOS = [
    ("Core use case - an approved change the firmware manual does not yet reflect",
     "Drive M4 trips with fault 5091 after operating for ten minutes.",
     [GovernanceMode.STRICT]),
    ("Governance mode - an authorised approval given in Teams, with no formal record",
     "What regular maintenance does the manual specify for softstarter S2?",
     [GovernanceMode.STRICT, GovernanceMode.FLEXIBLE]),
    ("Authorised approver involved, approval not confirmed",
     "What EOL trip class should softstarter S1 use?",
     [GovernanceMode.STRICT]),
    ("Approved, but the authority had lapsed on the decision date",
     "What are the coil operating limits for contactor K2?",
     [GovernanceMode.STRICT]),
    ("A technician's 'cancellation' has no authority; the approval stands",
     "What tightening torque do the main terminals of contactor K2 need?",
     [GovernanceMode.STRICT]),
    ("An approval cancelled by someone with authority to cancel it",
     "Is a transformer protection breaker still required for P5?",
     [GovernanceMode.STRICT]),
    ("Same fault code, different product family - no leakage",
     "Drive M9 shows fault 5091 Safe torque off, what should I check?",
     [GovernanceMode.STRICT]),
    ("Equipment not identified - answer withheld",
     "Fault 5091 keeps coming back on the drive, what should I check?",
     [GovernanceMode.STRICT]),
]


def block(answer) -> str:
    L = [f"**Equipment:** {answer.equipment_summary}  ",
         f"**Confidence:** {answer.equipment_confidence:.2f}  ",
         f"**Governance mode:** {answer.mode.value}  ",
         f"**Documentation status:** {answer.status.value}", ""]
    if answer.clarification_needed:
        L += ["> " + answer.clarification_needed, ""]
    if answer.guidance:
        L.append("**Guidance from the current documentation**")
        L += [f"{i}. {s.text}  \n   `{s.citations[0].label}`"
              for i, s in enumerate(answer.guidance, 1)] + [""]
    if answer.applicable_documents:
        L += ["**Applicable documents**"] + [f"- {d}" for d in answer.applicable_documents] + [""]
    if answer.pending_change:
        L += ["**Potential approved update not yet in the document**", "", answer.pending_change, "",
              "**Approval evidence**"] + [f"- {e}" for e in answer.approval_evidence] + [""]
    if answer.other_open_changes:
        L += ["**Other approved changes open against this asset**"] + \
             [f"- {e}" for e in answer.other_open_changes] + [""]
    if answer.escalation:
        L += ["**Escalation**", "", answer.escalation, ""]
    if answer.evidence_considered:
        L += ["**Every record examined**", "",
              "| record | channel | decision | authority | outcome | why |", "|---|---|---|---|---|---|"]
        for d in answer.evidence_considered:
            why = d.detail[0].split(": ", 1)[-1] if d.detail else "all conditions satisfied"
            L.append(f"| {d.comm_id} | {d.channel.value} | {d.decision_state.value} | "
                     f"{d.authority_state.value} | {d.classification} | {why[:110]} |")
        L.append("")
    L += ["**Verification gates**", "", "| gate | result | detail |", "|---|---|---|"]
    L += [f"| {g.gate} | {'PASS' if g.passed else 'FAIL'} | {g.detail} |" for g in answer.gates]
    return "\n".join(L + [""])


def main() -> None:
    out = sys.argv[1] if len(sys.argv) > 1 else "demo_transcript.md"
    settings = Settings()
    settings.audit_path = tempfile.mkstemp(suffix=".jsonl")[1]
    corpus = build_corpus()
    p = build_pipeline(settings, corpus)

    s = corpus.summary()
    parts = [
        "# DocDrift demonstration transcript", "",
        "Generated by `scripts/demo.py`. Version-n documents are real ABB publications "
        "retrieved from ABB's public library; version n-1 and all enterprise records "
        "(people, roles, Teams messages, emails, change notices) are synthetic and are "
        "labelled as such everywhere they appear.", "",
        "| corpus | count |", "|---|---:|",
    ] + [f"| {k.replace('_', ' ')} | {v} |" for k, v in s.items()] + [""]

    for title, question, modes in SCENARIOS:
        parts += [f"## {title}", "", f"> {question}", ""]
        for mode in modes:
            answer, _ = p.ask(question, mode=mode)
            if len(modes) > 1:
                parts.append(f"### Governance mode: {mode.value}")
                parts.append("")
            parts += [block(answer), ""]
        parts += ["---", ""]

    with open(out, "w") as fh:
        fh.write("\n".join(parts))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
