"""Storage protocols.

The three concrete stores shipped here (SQLite / local vector index / in-memory
graph) implement exactly these interfaces, so PostgreSQL, Qdrant and Neo4j drop
in without touching pipeline code.
"""
from __future__ import annotations

from datetime import date
from typing import Protocol, Sequence

from ..models import Chunk, Communication, DocumentVersion, Equipment, Person


class RecordStore(Protocol):
    def upsert_equipment(self, items: Sequence[Equipment]) -> None: ...
    def upsert_people(self, items: Sequence[Person]) -> None: ...
    def upsert_versions(self, items: Sequence[DocumentVersion]) -> None: ...
    def upsert_chunks(self, items: Sequence[Chunk]) -> None: ...
    def upsert_communications(self, items: Sequence[Communication]) -> None: ...

    def all_equipment(self) -> list[Equipment]: ...
    def get_equipment(self, asset_tag: str) -> Equipment | None: ...
    def get_person(self, person_id: str) -> Person | None: ...
    def versions_for_doc(self, doc_id: str) -> list[DocumentVersion]: ...
    def versions_for_family(self, family: str) -> list[DocumentVersion]: ...
    def chunks_for(self, doc_id: str, version: str) -> list[Chunk]: ...
    def get_chunk(self, chunk_id: str) -> Chunk | None: ...
    def communications_since(self, since: date) -> list[Communication]: ...


class VectorStore(Protocol):
    def index(self, ids: Sequence[str], texts: Sequence[str], payloads: Sequence[dict]) -> None: ...
    def search(self, query: str, top_k: int, where: dict | None = None) -> list[tuple[str, float]]: ...
    def vector_for(self, item_id: str): ...


class GraphStore(Protocol):
    def add_node(self, node_id: str, label: str, **props) -> None: ...
    def add_edge(self, src: str, rel: str, dst: str) -> None: ...
    def neighbors(self, node_id: str, rel: str | None = None) -> list[tuple[str, str]]: ...
    def path(self, src: str, dst: str, max_depth: int = 4) -> list[str]: ...
